"""Utilities for interacting with RGZ raw data."""

from collections.abc import Iterator
import json
import logging
from typing import Any
import warnings

from astropy.io import fits
from astropy.wcs import WCS
from astropy.coordinates import SkyCoord
import astropy.wcs
import numpy as np
import requests

from rgz import constants
from rgz import units as u

# TODO(MatthewJA): This file contains much legacy code and needs updating.

logger = logging.getLogger(__name__)

# A string storing coordinates in HMSDMS format,
# as generated by astropy, with a space-separator.
# i.e. "HH MM SS.SS* [+-]DD MM SS.SS*"
type HMSDMS = str

# A JSON-serialisable dict.
type JSON = dict[str, Any]


def safe_skycoord_iterable(coords: SkyCoord) -> Iterator[SkyCoord]:
    """Type-safe tabular SkyCoord."""
    return iter(coords)  # type: ignore[reportReturnType]


def get_deg(coord: SkyCoord) -> tuple[np.float64, np.float64]:
    """Gets the RA/dec of a SkyCoord in degrees."""
    return coord.ra.deg, coord.dec.deg  # type: ignore[reportReturnType]


def get_wcs(im: fits.HDUList) -> astropy.wcs.WCS:
    header = im[0].header  # type: ignore[reportAttributeAccessIssue]
    # WCS.dropaxis doesn't seem to work on these images.
    # Drop these: CTYPE3 CRVAL3 CDELT3 CRPIX3 CROTA3...
    for key in ["CTYPE", "CRVAL", "CDELT", "CRPIX", "CROTA"]:
        for i in [3, 4]:
            del header[key + str(i)]

    with warnings.catch_warnings(
        action="ignore", category=astropy.wcs.FITSFixedWarning
    ):
        return WCS(header)


def coord_to_string(coord: SkyCoord) -> HMSDMS:
    """Converts a SkyCoord to a string."""
    coord_str = coord.to_string("hmsdms", sep=" ")
    if not isinstance(coord_str, str):
        # SkyCoord.to_string is not guaranteed to return a string.
        raise TypeError(f"Expected str from SkyCoord.to_string; got {type(coord_str)}")
    return coord_str
