[project]
name = "rgz"
version = "0.0.0"
description = "rgz is the second incarnation data reduction pipeline for Radio Galaxy Zoo."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attrs",
    "requests",
    "matplotlib",
    "pandas",
    "tqdm",
    "astropy",
    "astroquery",
    "backoff",
    "black",
    "ipympl",
    "scipy",      # Needed for astropy.
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pytest",
]

[project.optional-dependencies]
cli = ["click"]
notebooks = ["jupyterlab", "jupyter", "notebook", "jupyterlab-code-formatter"]
profile = ["line_profiler"]

[project.scripts]
rgz = "rgz.main:cli"

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.10.6,<0.11.0"]

[tool.uv]
package = true

[tool.uv.build-backend]
module-root = ""

[tool.uv.sources]
rgz = { editable = true, path = "rgz"}

[tool.setuptools.packages.find]
where = ["."]
include = ["rgz"]

[tool.pytest.ini_options]
addopts = "--tb=short"
